#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#282828"
bspc config active_border_color "#928374"
bspc config focused_border_color "#d79921"
bspc config presel_feedback_color "#98971a"

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
$HOME/.config/polybar/launch.sh &
nm-applet &
blueman-applet &
# $HOME/.fehbg &
nitrogen --restore &
picom &
flameshot &
