preload = /home/luan/Pictures/wallpapers/lighthouse_night_landscape_143019_2560x1080.jpg
wallpaper = HDMI-A-1, /home/luan/Pictures/wallpapers/lighthouse_night_landscape_143019_2560x1080.jpg
wallpaper = eDP-1, /home/luan/Pictures/wallpapers/lighthouse_night_landscape_143019_2560x1080.jpg
splash = false
